version: '3.5'
services:
    backend:
        build: .
        command: npm run start:dev
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - "3000:3000"
        environment:
            DB_HOST: mysql
            API_LAYER_KEY: 621dcdd19de64bc657eaaae5a184e6fb
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: Tasklist
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
        volumes:
            - db-volume:/var/lib/mysql
volumes:
    db-volume: